import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ImageNotice, SectionHeading } from "@/components/techguru";
import { games } from "@/lib/techguru-content";

export const Route = createFileRoute("/games")({ head: () => ({ meta: [{ title: "Games Library | TECHGURU Marondera" }, { name: "description", content: "Explore editable PlayStation and VR game placeholders for TECHGURU gaming centre in Marondera." }, { property: "og:title", content: "Games Library | TECHGURU Marondera" }, { property: "og:description", content: "Browse the future VR and PlayStation game library at TECHGURU." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: GamesPage });

const filters = ["ALL", "PLAYSTATION", "VR", "RACING", "SPORTS", "FIGHTING", "ADVENTURE", "MULTIPLAYER"];
function GamesPage() { const [filter, setFilter] = useState("ALL"); const [query, setQuery] = useState(""); const shown = useMemo(() => games.filter((game) => (filter === "ALL" || game.platform.toUpperCase() === filter || game.genre.toUpperCase() === filter) && `${game.title} ${game.platform} ${game.genre}`.toLowerCase().includes(query.toLowerCase())), [filter, query]); return <section className="section-shell min-h-screen pt-32"><SectionHeading eyebrow="GAME FINDER" title="FIND YOUR NEXT GAME." copy="The current selection is awaiting confirmation. These editable placeholders show how the library will work." /><div className="mt-10 flex flex-col gap-4"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search the game library" className="pl-10" aria-label="Search games" /></div><div className="flex flex-wrap gap-2">{filters.map((item) => <Button key={item} variant={filter === item ? "default" : "outline"} size="sm" onClick={() => setFilter(item)}>{item}</Button>)}</div></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{shown.map((game) => <article key={game.id} className="game-card"><div className="relative aspect-video overflow-hidden"><img src={game.image} alt={`Illustrative ${game.genre} game placeholder`} width={1600} height={1200} loading="lazy" className="h-full w-full object-cover" /><ImageNotice /></div><div className="p-5"><span className="status">{game.availability}</span><h2 className="mt-4 font-display text-xl font-black uppercase">{game.title}</h2><p className="mt-2 text-xs font-bold uppercase text-primary">{game.platform} · {game.genre}</p><p className="mt-3 text-sm text-muted-foreground">{game.description}</p></div></article>)}</div>{shown.length === 0 && <p className="mt-12 text-muted-foreground">No placeholders match that search.</p>}</section>; }