import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { ArrowRight, ImageNotice, PageHero, SectionHeading, images } from "@/components/techguru";
import { games, messages, whatsappUrl } from "@/lib/techguru-content";

export const Route = createFileRoute("/playstation")({ head: () => ({ meta: [{ title: "PlayStation Gaming Marondera | TECHGURU" }, { name: "description", content: "Challenge your crew with PlayStation gaming at TECHGURU in Marondera, Zimbabwe." }, { property: "og:title", content: "PlayStation Gaming Marondera | TECHGURU" }, { property: "og:description", content: "Console competition, multiplayer fun and group gaming in Marondera." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: PlayStationPage });

function PlayStationPage() { const psGames = games.filter((game) => game.platform === "PlayStation"); return <>
  <PageHero eyebrow="PLAYSTATION AT TECHGURU" title="YOUR CONSOLE. YOUR CREW. YOUR GAME." copy="Settle in, pick up a controller and bring the competition. PlayStation gaming built for friends, rivals and great moments." image={images.console} imageAlt="Illustrative multiplayer console gaming experience"><Button asChild size="lg"><a href={whatsappUrl(messages.playstation)} target="_blank" rel="noreferrer">ENQUIRE NOW <ArrowRight /></a></Button></PageHero>
  <section className="section-shell"><SectionHeading eyebrow="GAME LIBRARY" title="PICK YOUR NEXT CHALLENGE." copy="Specific games are placeholders until TECHGURU confirms its current library." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{psGames.map((game) => <article key={game.id} className="game-card"><div className="relative aspect-[4/3] overflow-hidden"><img src={game.image} alt="Illustrative console game placeholder" width={1600} height={1200} loading="lazy" className="h-full w-full object-cover" /><ImageNotice /></div><div className="p-6"><span className="status">{game.availability}</span><h2 className="mt-4 font-display text-xl font-black uppercase">{game.title}</h2><p className="mt-2 text-xs font-bold uppercase text-primary">{game.platform} · {game.genre}</p><p className="mt-3 text-sm text-muted-foreground">{game.description}</p></div></article>)}</div><Button asChild variant="outline" className="mt-8"><Link to="/games">VIEW ALL GAME PLACEHOLDERS</Link></Button></section>
  <section className="section-shell bg-surface"><div className="grid items-center gap-10 lg:grid-cols-2"><div className="relative overflow-hidden"><img src={images.console} alt="Illustrative group console gaming" width={1600} height={1200} loading="lazy" className="aspect-[4/3] w-full object-cover" /><ImageNotice /></div><SectionHeading eyebrow="MULTIPLAYER ENERGY" title="CHALLENGE YOUR FRIENDS." copy="Share the screen, test your skills and make every round count. TECHGURU brings competitive PlayStation gaming to Marondera." /></div></section>
  </>; }